name: "Prepare npmrc"
description: "Prepares the .npmrc file with the required creds"
inputs:
  NPM_TOKEN:
    description: "The npm token to be set in .npmrc"
    required: true
  GITHUB_TOKEN:
    description: "The GitHub token to be set in .npmrc"
    required: true
runs:
  using: composite
  steps:
    - name: prepare npmrc
      run: |
        echo "//registry.npmjs.org/:_authToken=${{inputs.NPM_TOKEN}}" >> .npmrc
        echo "//npm.pkg.github.com/:_authToken=${{inputs.GITHUB_TOKEN}}" >> .npmrc
        echo "@extrahorizon:registry=https://npm.pkg.github.com" >> .npmrc
        echo "@fibricheck:registry=https://npm.pkg.github.com" >> .npmrc
      shell: bash
