name: "Prepare npmrc"
description: "Prepares the .npmrc file with the required creds"

runs:
  using: composite
  steps:
    - name: prepare npmrc
      run: |
        echo "//registry.npmjs.org/:_authToken=${{inputs.NPM_TOKEN}}" > .npmrc
        echo "//npm.pkg.github.com/:_authToken=${{inputs.GITHUB_TOKEN}}" >> .npmrc
        echo "@extrahorizon:registry=https://npm.pkg.github.com" >> .npmrc
        echo "@fibricheck:registry=https://npm.pkg.github.com" >> .npmrc
      shell: sh
